src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock_counter;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStockCounter(): ?int
    {
        return $this->stock_counter;
    }

    public function setStockCounter(?int $stock_counter): self
    {
        $this->stock_counter = $stock_counter;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price/100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function __construct()
    {
        $this->stock_counter = 0;
    }
}

src/Controller/HomeController.php
<?php


namespace App\Controller;


use App\Repository\ProductRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="app_home_index")
     *
     */
    public function index(ProductRepository $productRepository, PaginatorInterface $paginator, Request $request)
    {
        $products = $productRepository->findPossibleToSell();
        return $this->render('Home/index.html.twig', [
            'products' => $paginator->paginate($products, $request->query->getInt('page', 1), 4)
        ]);
    }
}

templates/Home/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ parent() }} - Strona główna{% endblock %}
{% block body %}
    <h5>Produkty</h5>
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <p class="alert alert-{{ label }}">
                {{ message }}
            </p>
        {% endfor %}
    {% endfor %}
    {% if products is not empty %}
        <div class="products">
            <table>
                <tr>
                    <th>Nazwa produktu</th>
                    <th>Cena</th>
                    <th>Dostępna ilość</th>
                    <th>Operacje</th>
                </tr>
                {% for product in products %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td>{{ product.price | number_format(2, ',', ' ') }}zł</td>
                        <td>{{ product.stockCounter }}</td>
                        <td>
                            <form action="{{ path('app_cart_add') }}" method="post">
                                <input type="hidden" value="{{ product.id }}" name="id">
                                <input type="number" name="count" placeholder="Ilość" required="required">
                                <input type="submit" value="Dodaj do koszyka">
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <div class="navigation">
                {{ knp_pagination_render(products) }}
            </div>
        </div>
    {% else %}
        <p class="alert">Brak produktów na sprzedaż</p>
    {% endif %}
{% endblock %}